development:
FB_PAGE_KEY: 'EAAB0ueAeCC4BAJlQ2ZCZAwuC7fEkD1ARc7pxOIvotFkvy4PWyDgmqaDNM4xkZCnM8fDuL8MjFxeCYLNuf0Jegi4idTDaRcRwCZBFvmsSqZCWwrUU148HC7LiZBTlBNp15t5cpEN2rDHIYeaZCkMdYjWYD5cKsH8rLlkv7i4cw1SMHUlBqhvdGRb'
FB_SECRET_PASS: '11a27f300e917ae0d16e24bd6cdd53f9'

staging:
FB_PAGE_KEY: 'EAAB0ueAeCC4BAJlQ2ZCZAwuC7fEkD1ARc7pxOIvotFkvy4PWyDgmqaDNM4xkZCnM8fDuL8MjFxeCYLNuf0Jegi4idTDaRcRwCZBFvmsSqZCWwrUU148HC7LiZBTlBNp15t5cpEN2rDHIYeaZCkMdYjWYD5cKsH8rLlkv7i4cw1SMHUlBqhvdGRb'
FB_SECRET_PASS: '11a27f300e917ae0d16e24bd6cdd53f9'

production:
FB_PAGE_KEY: 'EAAB0ueAeCC4BAJlQ2ZCZAwuC7fEkD1ARc7pxOIvotFkvy4PWyDgmqaDNM4xkZCnM8fDuL8MjFxeCYLNuf0Jegi4idTDaRcRwCZBFvmsSqZCWwrUU148HC7LiZBTlBNp15t5cpEN2rDHIYeaZCkMdYjWYD5cKsH8rLlkv7i4cw1SMHUlBqhvdGRb'
FB_SECRET_PASS: '11a27f300e917ae0d16e24bd6cdd53f9'
