development:
FB_PAGE_KEY: 'EAAB0ueAeCC4BAJlQ2ZCZAwuC7fEkD1ARc7pxOIvotFkvy4PWyDgmqaDNM4xkZCnM8fDuL8MjFxeCYLNuf0Jegi4idTDaRcRwCZBFvmsSqZCWwrUU148HC7LiZBTlBNp15t5cpEN2rDHIYeaZCkMdYjWYD5cKsH8rLlkv7i4cw1SMHUlBqhvdGRb'
FB_SECRET_PASS: '11a27f300e917ae0d16e24bd6cdd53f9'
FB_URL: "https://graph.facebook.com/me/messages?access_token="
FB_APP_ID: "128341677836334"
FB_PAGE_ID: "148583745871092"

staging:
FB_PAGE_KEY: 'EAAB0ueAeCC4BAJlQ2ZCZAwuC7fEkD1ARc7pxOIvotFkvy4PWyDgmqaDNM4xkZCnM8fDuL8MjFxeCYLNuf0Jegi4idTDaRcRwCZBFvmsSqZCWwrUU148HC7LiZBTlBNp15t5cpEN2rDHIYeaZCkMdYjWYD5cKsH8rLlkv7i4cw1SMHUlBqhvdGRb'
FB_SECRET_PASS: '11a27f300e917ae0d16e24bd6cdd53f9'
FB_URL: "https://graph.facebook.com/me/messages?access_token="
FB_APP_ID: "128341677836334"
FB_PAGE_ID: "148583745871092"

production:
FB_PAGE_KEY: 'EAAB0ueAeCC4BAJlQ2ZCZAwuC7fEkD1ARc7pxOIvotFkvy4PWyDgmqaDNM4xkZCnM8fDuL8MjFxeCYLNuf0Jegi4idTDaRcRwCZBFvmsSqZCWwrUU148HC7LiZBTlBNp15t5cpEN2rDHIYeaZCkMdYjWYD5cKsH8rLlkv7i4cw1SMHUlBqhvdGRb'
FB_SECRET_PASS: '11a27f300e917ae0d16e24bd6cdd53f9'
FB_URL: "https://graph.facebook.com/me/messages?access_token="
FB_APP_ID: "128341677836334"
FB_PAGE_ID: "148583745871092"
